name: Build

on: push

env:
  TZ: Asia/Shanghai

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
          cache: maven
      - run: mvn --batch-mode -am -pl cdc,canal verify
      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/master'
        with:
          name: jar
          path: |
            cdc/target/vault-cdc-0.0.1-SNAPSHOT.jar
            canal/target/vault-canal-0.0.1-SNAPSHOT.jar
          retention-days: 5
